/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-error-container": "#ffa8a3",
              "surface-container-low": "var(--color-surface-container-low)",
              "surface-container": "var(--color-surface-container)",
              "secondary-dim": "#8197ff",
              "primary-fixed-dim": "#5690ff",
              "surface-variant": "var(--color-surface-container-highest)",
              "surface-container-highest": "var(--color-surface-container-highest)",
              "tertiary": "#feb7ff",
              "on-tertiary-fixed": "#4a0054",
              "on-error": "#490006",
              "outline-variant": "var(--color-outline-variant)",
              "error-container": "#9f0519",
              "on-tertiary": "#702379",
              "error-dim": "#d7383b",
              "surface-tint": "var(--color-primary)",
              "surface-container-high": "var(--color-surface-container-high)",
              "primary-fixed": "#6f9fff",
              "on-primary-container": "#002151",
              "secondary-fixed-dim": "#b5c0ff",
              "on-background": "var(--color-on-surface)",
              "primary-dim": "var(--color-primary-dim)",
              "on-primary-fixed-variant": "#002a63",
              "surface": "var(--color-surface)",
              "background": "var(--color-surface)",
              "on-surface-variant": "var(--color-on-surface-variant)",
              "outline": "#757575",
              "inverse-surface": "#f9f9f9",
              "tertiary-fixed-dim": "#ec94f0",
              "on-secondary": "#001661",
              "surface-bright": "#2c2c2c",
              "secondary": "#8197ff",
              "on-secondary-fixed": "#05278f",
              "primary-container": "#6f9fff",
              "tertiary-dim": "#ec94f0",
              "on-tertiary-fixed-variant": "#702379",
              "inverse-on-surface": "#555555",
              "on-surface": "var(--color-on-surface)",
              "on-secondary-container": "#c6ceff",
              "error": "#ff716c",
              "on-primary-fixed": "#000000",
              "on-tertiary-container": "#65186f",
              "tertiary-fixed": "#fba1ff",
              "surface-container-lowest": "var(--color-surface-container-lowest)",
              "inverse-primary": "#005ac6",
              "tertiary-container": "#fba1ff",
              "surface-dim": "var(--color-surface)",
              "primary": "var(--color-primary)",
              "on-secondary-fixed-variant": "#2f47ac",
              "secondary-fixed": "#c7cfff",
              "secondary-container": "#233ca1",
              "on-primary": "#002c67"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
