/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-error-container": "#ffa8a3",
              "surface-container-low": "#131313",
              "surface-container": "#191919",
              "secondary-dim": "#8197ff",
              "primary-fixed-dim": "#5690ff",
              "surface-variant": "#262626",
              "surface-container-highest": "#262626",
              "tertiary": "#feb7ff",
              "on-tertiary-fixed": "#4a0054",
              "on-error": "#490006",
              "outline-variant": "#484848",
              "error-container": "#9f0519",
              "on-tertiary": "#702379",
              "error-dim": "#d7383b",
              "surface-tint": "#87adff",
              "surface-container-high": "#1f1f1f",
              "primary-fixed": "#6f9fff",
              "on-primary-container": "#002151",
              "secondary-fixed-dim": "#b5c0ff",
              "on-background": "#ffffff",
              "primary-dim": "#006ff0",
              "on-primary-fixed-variant": "#002a63",
              "surface": "#0e0e0e",
              "background": "#0e0e0e",
              "on-surface-variant": "#ababab",
              "outline": "#757575",
              "inverse-surface": "#f9f9f9",
              "tertiary-fixed-dim": "#ec94f0",
              "on-secondary": "#001661",
              "surface-bright": "#2c2c2c",
              "secondary": "#8197ff",
              "on-secondary-fixed": "#05278f",
              "primary-container": "#6f9fff",
              "tertiary-dim": "#ec94f0",
              "on-tertiary-fixed-variant": "#702379",
              "inverse-on-surface": "#555555",
              "on-surface": "#ffffff",
              "on-secondary-container": "#c6ceff",
              "error": "#ff716c",
              "on-primary-fixed": "#000000",
              "on-tertiary-container": "#65186f",
              "tertiary-fixed": "#fba1ff",
              "surface-container-lowest": "#000000",
              "inverse-primary": "#005ac6",
              "tertiary-container": "#fba1ff",
              "surface-dim": "#0e0e0e",
              "primary": "#87adff",
              "on-secondary-fixed-variant": "#2f47ac",
              "secondary-fixed": "#c7cfff",
              "secondary-container": "#233ca1",
              "on-primary": "#002c67"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
